//
//  SearchResult.swift
//  BookStoreKit
//
//  Created by Soojin Ro on 13/06/2019.
//  Copyright © 2019 Soojin Ro. All rights reserved.
//

import Foundation

/// The search result generated by search request.
public struct SearchResult {
    
    /// The request object associated with the search result.
    ///
    /// Use this instance to 
    /// - note: SearchEngine will always yield result with the latest search keyword.
    public let request: SearchRequest
    
    /// The collection of books containing the search keyword in its information.
    public let books: [Book]
    
    init(books: [Book], searchText: String, page: Int) {
        self.request = SearchRequest(text: searchText, page: page)
        self.books = books
    }
}
